let saludo = "¡Hola Mundo!";
let nombre = "Juan";
let array = [1,2,3,4,5];
console.log("¡Hola Mundo! Soy", nombre);
console.log("Mi nombre en mayúsculas es:", nombre.toUpperCase());
console.log("Mi nombre en minúsculas es:", nombre.toLowerCase());
console.log("El mensaje de", saludo, "tiene", saludo.length, "caracteres.");
console.log("El tercer número del array con los valores", array, "es:", array[2]);
array.push(6);
console.log("Se añade el número que sigue al final del arreglo y es:", array[array.length - 1]);